'use client'
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navlayout from './Layout/Navlayout';
import { usePathname } from 'next/navigation';
import { HeroUIProvider } from "@heroui/react";
import AIAssistantButton from "./components/AIAssistantButton"; // Yeni bileşeni import et

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const hideNav = ['/login', '/register','/dashboard','/editsettings'].some((route) => pathname.startsWith(route));

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
         <Toaster position="top-center" reverseOrder={false} />
         <HeroUIProvider>
        {!hideNav && <Navlayout />}
        
        {children}
        <AIAssistantButton /> {/* Butonu buraya ekle */}
        </HeroUIProvider>
      </body>
    </html>
  );
}
